### PR TITLE
Create an RSS feed for the Articles

### PR DESCRIPTION
**Pull request by virtualroot**
Hello folks :wave: 

I wanted to add https://greensoftware.foundation/articles to my feed reader.
At the moment, it isn't being generated. This pull request adds the functionality.

The changes are as follows:
 - Install gatsby-plugin-feed@v4 plugin.
 - Reuse bits from articles-list.js GraphQL query to generate the feed.
 - `rss.xml` file was validated against https://validator.w3.org/feed/. :heavy_check_mark: 
 
 To test the RSS feed locally, you'll have to run a build:
 
 `$ npm run build && cat public/rss.xml`

### CODE REVIEW

**Comment by virtualroot** [comment]
Hello folks! How can I help get this feature merged? :rocket: 

/cc @osamajandali @shuuji3

**Comment by russelltrow** [comment]
Hi @virtualroot thank you so much for taking the time to implement this functionality. 

@osamajandali @zanete how shall we proceed here?

**Comment by zanete** [comment]
@russelltrow We'll add this to the web sprint and I will get an update to you shorly. thanks for the tag

**Comment by zanete** [comment]
@osamajandali will review this week

**Comment by osamajandali** [comment]
Thanks so much @virtualroot ! this is a great addition.
Do you think we should reference that somewhere in the articles page so people who need it find it ?

**Comment by osamajandali** [comment]
@zanete if you want the rss in a link only then we are good to go. but if need to add the link in the article page in the website then let's first add it before merge

**Comment by zanete** [comment]
@osamajandali  we are good to merge without a link for now, thanks! 🙏

**Comment by virtualroot** [comment]
Just so you know – the RSS icon isn't needed, but it is welcome to signal its presence.

RSS apps do autodiscovery with an HTML link tag.
`<link rel="alternate" type="application/rss+xml" title="Green Software Foundation RSS Feed" href="/rss.xml"/>`

I tried with [mine](https://addons.mozilla.org/en-US/firefox/addon/brook-feed-reader/), and it works. :100: 

Thank you all!

**Pull request merged**
